services:
  # PostgreSQL database service for development
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gradeinator_dev

  # Flask application service - Development
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "${DEV_PORT}:5000"
    volumes:
      # Mount code for live reloading
      - .:/app
      - /app/__pycache__
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ${FLASK_APP}
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
    depends_on:
      - db
    networks:
      - gradeinator_dev
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  db_data_dev:

networks:
  gradeinator_dev:
    driver: bridge 